# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "prod-rails-bank-trx-reporting-deploy"
    encrypt = true
    key     = "ecs.prod.terraform.tfstate"
    region  = "ca-central-1"
  }
}
