   name: tf_shiftleft

   on:
     pull_request:
       branches:
         - main
     push:
       branches:
         - main

   jobs:
     lint_docs_plan_test:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.10.1

       # Step 1: Lint with tflint
       - name: Install tflint
         run: |
           curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

       - name: Run tflint
         working-directory: infra-deployment
         run: tflint
         continue-on-error: true

       # Step 2: Generate documentation with tfdocs
       - name: Generate terraform docs
         uses: actions/checkout@v3
         with:
          ref: ${{ github.event.pull_request.head.ref }}

       - name: Render terraform docs and push changes back to PR
         uses: terraform-docs/gh-actions@main
         with:
          working-dir: .
          output-file: infra-deployment/tfdocs.md
          output-method: inject
          git-push: "true"

         # Step 3: Terraform Plan
       - name: Terraform Init
         working-directory: infra-deployment
         run: terraform init

       - name: Terraform Plan
         id: plan
         working-directory: infra-deployment
         run: terraform plan

       # Step 4: Terraform Testing with checkov
       - name: Install Checkov
         run: pip install checkov

       - name: Run Checkov for security testing
         working-directory: infra-deployment
         run: checkov -d .